# Generated by Django 5.0.6 on 2024-06-14 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nis', models.CharField(max_length=10, unique=True)),
                ('driver_number', models.CharField(max_length=255)),
                ('driver_code', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=255)),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('date_of_medical', models.DateField(blank=True, verbose_name='date of medical exam')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='registration date')),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.sex')),
            ],
        ),
    ]
