# Generated by Django 5.0.6 on 2024-06-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_rename_driver_owner'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owners',
            field=models.ManyToManyField(to='owners.owner'),
        ),
    ]
