# Generated by Django 5.0.6 on 2024-06-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspectors', '0001_initial'),
        ('offices', '0001_initial'),
        ('owners', '0002_rename_driver_owner'),
        ('vehicles', '0002_vehicle_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspectors.inspector')),
                ('owner', models.ManyToManyField(to='owners.owner')),
                ('paid_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.location')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
                ('insurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurers.insurer')),
            ],
        ),
    ]
