# Generated by Django 5.0.6 on 2024-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='insured',
            name='date_insured',
            field=models.DateField(blank=True, null=True),
        ),
    ]
