# Generated by Django 5.0.6 on 2024-06-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0003_alter_insured_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='owner',
        ),
    ]
