# Generated by Django 5.0.6 on 2024-06-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_rename_driver_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='sex',
        ),
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.gender'),
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
