# Generated by Django 5.0.6 on 2024-06-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0002_remove_insured_paid_at_insured_date_insured'),
        ('licences', '0001_initial'),
        ('offices', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('receipt_number', models.CharField(max_length=255, unique=True)),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurers.insured')),
                ('paid_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.location')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurances', to='transactions.transactiontype')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('receipt_number', models.CharField(max_length=255, unique=True)),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licences.licence')),
                ('paid_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offices.location')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licences', to='transactions.transactiontype')),
            ],
        ),
    ]
