# Generated by Django 5.0.6 on 2024-06-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionvehicle',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactionlicence',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactioninsurance',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
